# This is a basic workflow to help you get started with Actions

name: Flutter Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Run Flutter Test and check percentage
        run: flutter test --coverage
      - name: Build APP BUNDLE
        run: flutter build appbundle --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: release-apk
          path: build/app/outputs/apk/release/*