# This is a basic workflow to help you get started with Actions

name: Build workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ios-android:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: dart format
        run: dart format --set-exit-if-changed .

      - name: Flutter analyze
        run: flutter analyze

      - name: Run Flutter Test and check percentage
        run: flutter test --coverage

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report Code Coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 20
          artifact-name: code-coverage-report
          github-token: ${{github.token}}

#      - name: Build APP BUNDLE
#        run: flutter build apk --build-number=${{github.run_number}}
#
#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v3.1.0
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/*
#
#      - name: Firebase App Distribution for Android
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
#          groups: testers
#          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Build ios App
        run: flutter build ios --no-codesign --build-number=${{github.run_number}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Runner
          path: build/ios/iphoneos/*

  distribute-ios:
    needs: build-ios-android # This is important
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Runner

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_IOS_APP_ID}}
          file: Runner
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers